# Generated by Django 2.1.1 on 2018-10-02 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='upi_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
