# Generated by Django 2.1.1 on 2018-10-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank',
            field=models.CharField(default='ICICI', max_length=10),
        ),
    ]
