# Generated by Django 2.1.1 on 2018-10-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bank_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='id',
        ),
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(default='97811564554563433474', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
