# Generated by Django 2.1.1 on 2018-10-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181004_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='init',
            new_name='iv',
        ),
    ]
