# Generated by Django 2.1.1 on 2018-10-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.CharField(default='ICICI', max_length=30),
        ),
    ]
